version: "3"

services:
  nginx:
    init: true
    image: nginx:latest
    ports:
      - "127.0.0.1:13030:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /home/bhavesh/mounts/hdd/app-data/store/nix-cache/:/data/
    restart: unless-stopped
